package com.ftme.common.model;

import com.jfinal.plugin.activerecord.ActiveRecordPlugin;

/**
 * Generated by JFinal, do not modify this file.
 * <pre>
 * Example:
 * public void configPlugin(Plugins me) {
 *     ActiveRecordPlugin arp = new ActiveRecordPlugin(...);
 *     _MappingKit.mapping(arp);
 *     me.add(arp);
 * }
 * </pre>
 */
public class _MappingKit {

	public static void mapping(ActiveRecordPlugin arp) {
		arp.addMapping("clinical", "id", Clinical.class);
		arp.addMapping("companyinfo", "id", Companyinfo.class);
		arp.addMapping("documentinfo", "id", Documentinfo.class);
		arp.addMapping("hospital", "id", Hospital.class);
		arp.addMapping("interactive", "id", Interactive.class);
		arp.addMapping("items", "id", Items.class);
		arp.addMapping("news", "id", News.class);
		arp.addMapping("permissions", "id", Permissions.class);
		arp.addMapping("pictureinfo", "id", Pictureinfo.class);
		arp.addMapping("role", "id", Role.class);
		arp.addMapping("rolepermissions", "id", Rolepermissions.class);
		arp.addMapping("smsrecord", "id", Smsrecord.class);
		arp.addMapping("testresults", "id", Testresults.class);
		arp.addMapping("userinfo", "id", Userinfo.class);
	}
}

