package com.ftme.common.model;

import com.ftme.common.model.base.BaseClinical;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Clinical extends BaseClinical<Clinical> {
	public static final Clinical dao = new Clinical();
}
