package com.ftme.common.model;

import com.ftme.common.model.base.BaseCompanyinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Companyinfo extends BaseCompanyinfo<Companyinfo> {
	public static final Companyinfo dao = new Companyinfo();
}
