package com.ftme.common.model;

import com.ftme.common.model.base.BaseDocumentinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Documentinfo extends BaseDocumentinfo<Documentinfo> {
	public static final Documentinfo dao = new Documentinfo();
}
