package com.ftme.common.model;

import com.ftme.common.model.base.BaseHospital;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Hospital extends BaseHospital<Hospital> {
	public static final Hospital dao = new Hospital();
}
