package com.ftme.common.model;

import com.ftme.common.model.base.BaseInteractive;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Interactive extends BaseInteractive<Interactive> {
	public static final Interactive dao = new Interactive();
}
