package com.ftme.common.model;

import com.ftme.common.model.base.BaseItems;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Items extends BaseItems<Items> {
	public static final Items dao = new Items();
}
