package com.ftme.common.model;

import com.ftme.common.model.base.BasePermissions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Permissions extends BasePermissions<Permissions> {
	public static final Permissions dao = new Permissions();
}
