package com.ftme.common.model;

import com.ftme.common.model.base.BasePictureinfo;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Pictureinfo extends BasePictureinfo<Pictureinfo> {
	public static final Pictureinfo dao = new Pictureinfo();
}
