package com.ftme.common.model;

import com.ftme.common.model.base.BaseRolepermissions;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Rolepermissions extends BaseRolepermissions<Rolepermissions> {
	public static final Rolepermissions dao = new Rolepermissions();
}
