package com.ftme.common.model;

import com.ftme.common.model.base.BaseSmsrecord;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Smsrecord extends BaseSmsrecord<Smsrecord> {
	public static final Smsrecord dao = new Smsrecord();
}
