package com.ftme.common.model;

import com.ftme.common.model.base.BaseTestresults;

/**
 * Generated by JFinal.
 */
@SuppressWarnings("serial")
public class Testresults extends BaseTestresults<Testresults> {
	public static final Testresults dao = new Testresults();
}
