package com.ftme.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseUserinfo<M extends BaseUserinfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setUserNo(java.lang.String userNo) {
		set("userNo", userNo);
	}

	public java.lang.String getUserNo() {
		return get("userNo");
	}

	public void setRoleNo(java.lang.String roleNo) {
		set("roleNo", roleNo);
	}

	public java.lang.String getRoleNo() {
		return get("roleNo");
	}

	public void setRoleType(java.lang.String roleType) {
		set("roleType", roleType);
	}

	public java.lang.String getRoleType() {
		return get("roleType");
	}

	public void setHospitalNo(java.lang.String hospitalNo) {
		set("hospitalNo", hospitalNo);
	}

	public java.lang.String getHospitalNo() {
		return get("hospitalNo");
	}

	public void setHospitalname(java.lang.String hospitalname) {
		set("hospitalname", hospitalname);
	}

	public java.lang.String getHospitalname() {
		return get("hospitalname");
	}

	public void setUno(java.lang.String uno) {
		set("uno", uno);
	}

	public java.lang.String getUno() {
		return get("uno");
	}

	public void setDoctorname(java.lang.String doctorname) {
		set("doctorname", doctorname);
	}

	public java.lang.String getDoctorname() {
		return get("doctorname");
	}

	public void setClinicalname(java.lang.String clinicalname) {
		set("clinicalname", clinicalname);
	}

	public java.lang.String getClinicalname() {
		return get("clinicalname");
	}

	public void setItemsname(java.lang.String itemsname) {
		set("itemsname", itemsname);
	}

	public java.lang.String getItemsname() {
		return get("itemsname");
	}

	public void setTestresultsname(java.lang.String testresultsname) {
		set("testresultsname", testresultsname);
	}

	public java.lang.String getTestresultsname() {
		return get("testresultsname");
	}

	public void setUsername(java.lang.String username) {
		set("username", username);
	}

	public java.lang.String getUsername() {
		return get("username");
	}

	public void setPassword(java.lang.String password) {
		set("password", password);
	}

	public java.lang.String getPassword() {
		return get("password");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setSex(java.lang.Integer sex) {
		set("sex", sex);
	}

	public java.lang.Integer getSex() {
		return get("sex");
	}

	public void setEmail(java.lang.String email) {
		set("email", email);
	}

	public java.lang.String getEmail() {
		return get("email");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setCourierInfo(java.lang.String courierInfo) {
		set("courierInfo", courierInfo);
	}

	public java.lang.String getCourierInfo() {
		return get("courierInfo");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setDatetime(java.util.Date datetime) {
		set("datetime", datetime);
	}

	public java.util.Date getDatetime() {
		return get("datetime");
	}

	public void setAccountState(java.lang.Integer accountState) {
		set("accountState", accountState);
	}

	public java.lang.Integer getAccountState() {
		return get("accountState");
	}

	public void setEmailState(java.lang.Integer emailState) {
		set("emailState", emailState);
	}

	public java.lang.Integer getEmailState() {
		return get("emailState");
	}

	public void setCourierState(java.lang.String courierState) {
		set("courierState", courierState);
	}

	public java.lang.String getCourierState() {
		return get("courierState");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

}
