package com.ftme.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseCompanyinfo<M extends BaseCompanyinfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setCompanyName(java.lang.String companyName) {
		set("companyName", companyName);
	}

	public java.lang.String getCompanyName() {
		return get("companyName");
	}

	public void setCompanyPhone(java.lang.String companyPhone) {
		set("companyPhone", companyPhone);
	}

	public java.lang.String getCompanyPhone() {
		return get("companyPhone");
	}

	public void setCompanyAddress(java.lang.String companyAddress) {
		set("companyAddress", companyAddress);
	}

	public java.lang.String getCompanyAddress() {
		return get("companyAddress");
	}

	public void setCompanyIntroduce(java.lang.String companyIntroduce) {
		set("companyIntroduce", companyIntroduce);
	}

	public java.lang.String getCompanyIntroduce() {
		return get("companyIntroduce");
	}

	public void setCompanyEmail(java.lang.String companyEmail) {
		set("companyEmail", companyEmail);
	}

	public java.lang.String getCompanyEmail() {
		return get("companyEmail");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

}
