package com.ftme.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseRole<M extends BaseRole<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setRoleNo(java.lang.String roleNo) {
		set("roleNo", roleNo);
	}

	public java.lang.String getRoleNo() {
		return get("roleNo");
	}

	public void setRoleType(java.lang.String roleType) {
		set("roleType", roleType);
	}

	public java.lang.String getRoleType() {
		return get("roleType");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

}
