package com.ftme.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePictureinfo<M extends BasePictureinfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setPictureNo(java.lang.String pictureNo) {
		set("pictureNo", pictureNo);
	}

	public java.lang.String getPictureNo() {
		return get("pictureNo");
	}

	public void setPicturename(java.lang.String picturename) {
		set("picturename", picturename);
	}

	public java.lang.String getPicturename() {
		return get("picturename");
	}

	public void setPicturePath(java.lang.String picturePath) {
		set("picturePath", picturePath);
	}

	public java.lang.String getPicturePath() {
		return get("picturePath");
	}

	public void setContent(java.lang.String content) {
		set("content", content);
	}

	public java.lang.String getContent() {
		return get("content");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

}
