package com.ftme.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseDocumentinfo<M extends BaseDocumentinfo<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setDocumentNo(java.lang.String documentNo) {
		set("documentNo", documentNo);
	}

	public java.lang.String getDocumentNo() {
		return get("documentNo");
	}

	public void setUserNo(java.lang.String userNo) {
		set("userNo", userNo);
	}

	public java.lang.String getUserNo() {
		return get("userNo");
	}

	public void setHospitalNo(java.lang.String hospitalNo) {
		set("hospitalNo", hospitalNo);
	}

	public java.lang.String getHospitalNo() {
		return get("hospitalNo");
	}

	public void setHospitalname(java.lang.String hospitalname) {
		set("hospitalname", hospitalname);
	}

	public java.lang.String getHospitalname() {
		return get("hospitalname");
	}

	public void setDoctorNo(java.lang.String doctorNo) {
		set("doctorNo", doctorNo);
	}

	public java.lang.String getDoctorNo() {
		return get("doctorNo");
	}

	public void setDoctorname(java.lang.String doctorname) {
		set("doctorname", doctorname);
	}

	public java.lang.String getDoctorname() {
		return get("doctorname");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setDocumentType(java.lang.String documentType) {
		set("documentType", documentType);
	}

	public java.lang.String getDocumentType() {
		return get("documentType");
	}

	public void setDocumentName(java.lang.String documentName) {
		set("documentName", documentName);
	}

	public java.lang.String getDocumentName() {
		return get("documentName");
	}

	public void setDocumentUploadName(java.lang.String documentUploadName) {
		set("documentUploadName", documentUploadName);
	}

	public java.lang.String getDocumentUploadName() {
		return get("documentUploadName");
	}

	public void setUploadPath(java.lang.String uploadPath) {
		set("uploadPath", uploadPath);
	}

	public java.lang.String getUploadPath() {
		return get("uploadPath");
	}

	public void setDocumentPath(java.lang.String documentPath) {
		set("documentPath", documentPath);
	}

	public java.lang.String getDocumentPath() {
		return get("documentPath");
	}

	public void setAdmin(java.lang.String admin) {
		set("admin", admin);
	}

	public java.lang.String getAdmin() {
		return get("admin");
	}

	public void setRemark(java.lang.String remark) {
		set("remark", remark);
	}

	public java.lang.String getRemark() {
		return get("remark");
	}

	public void setDocumentState(java.lang.String documentState) {
		set("documentState", documentState);
	}

	public java.lang.String getDocumentState() {
		return get("documentState");
	}

	public void setDatetime(java.util.Date datetime) {
		set("datetime", datetime);
	}

	public java.util.Date getDatetime() {
		return get("datetime");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

}
