package com.ftme.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseClinical<M extends BaseClinical<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setClinicalNo(java.lang.String clinicalNo) {
		set("clinicalNo", clinicalNo);
	}

	public java.lang.String getClinicalNo() {
		return get("clinicalNo");
	}

	public void setClinicalname(java.lang.String clinicalname) {
		set("clinicalname", clinicalname);
	}

	public java.lang.String getClinicalname() {
		return get("clinicalname");
	}

	public void setClinicalState(java.lang.String clinicalState) {
		set("clinicalState", clinicalState);
	}

	public java.lang.String getClinicalState() {
		return get("clinicalState");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

}
