package com.ftme.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BaseSmsrecord<M extends BaseSmsrecord<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setSmsNo(java.lang.String smsNo) {
		set("smsNo", smsNo);
	}

	public java.lang.String getSmsNo() {
		return get("smsNo");
	}

	public void setUserNo(java.lang.String userNo) {
		set("userNo", userNo);
	}

	public java.lang.String getUserNo() {
		return get("userNo");
	}

	public void setName(java.lang.String name) {
		set("name", name);
	}

	public java.lang.String getName() {
		return get("name");
	}

	public void setPhone(java.lang.String phone) {
		set("phone", phone);
	}

	public java.lang.String getPhone() {
		return get("phone");
	}

	public void setSmsType(java.lang.String smsType) {
		set("smsType", smsType);
	}

	public java.lang.String getSmsType() {
		return get("smsType");
	}

	public void setSmsState(java.lang.String smsState) {
		set("smsState", smsState);
	}

	public java.lang.String getSmsState() {
		return get("smsState");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

}
