package com.ftme.common.model.base;

import com.jfinal.plugin.activerecord.Model;
import com.jfinal.plugin.activerecord.IBean;

/**
 * Generated by JFinal, do not modify this file.
 */
@SuppressWarnings("serial")
public abstract class BasePermissions<M extends BasePermissions<M>> extends Model<M> implements IBean {

	public void setId(java.lang.Integer id) {
		set("id", id);
	}

	public java.lang.Integer getId() {
		return get("id");
	}

	public void setPermissionsidNo(java.lang.String permissionsidNo) {
		set("permissionsidNo", permissionsidNo);
	}

	public java.lang.String getPermissionsidNo() {
		return get("permissionsidNo");
	}

	public void setHierarchy(java.lang.Integer hierarchy) {
		set("hierarchy", hierarchy);
	}

	public java.lang.Integer getHierarchy() {
		return get("hierarchy");
	}

	public void setPermissionsidName(java.lang.String permissionsidName) {
		set("permissionsidName", permissionsidName);
	}

	public java.lang.String getPermissionsidName() {
		return get("permissionsidName");
	}

	public void setIcon(java.lang.String icon) {
		set("icon", icon);
	}

	public java.lang.String getIcon() {
		return get("icon");
	}

	public void setLinkstyle(java.lang.String linkstyle) {
		set("linkstyle", linkstyle);
	}

	public java.lang.String getLinkstyle() {
		return get("linkstyle");
	}

	public void setMonikeri(java.lang.String monikeri) {
		set("monikeri", monikeri);
	}

	public java.lang.String getMonikeri() {
		return get("monikeri");
	}

	public void setLinkname(java.lang.String linkname) {
		set("linkname", linkname);
	}

	public java.lang.String getLinkname() {
		return get("linkname");
	}

	public void setSuperior(java.lang.String superior) {
		set("superior", superior);
	}

	public java.lang.String getSuperior() {
		return get("superior");
	}

	public void setState(java.lang.String state) {
		set("state", state);
	}

	public java.lang.String getState() {
		return get("state");
	}

}
